version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    environment:
      XCODE_SCHEME: peeriomobile
      PEERIO_IOS_SIM: 'iPhone 6 Plus'
      PEERIO_IOS_VERSION: '10.3'
      PEERIO_TEST_PLATFORM: 'ios'
    steps:
      - checkout
      - run:
          name: "Set PATH"
          command: echo "export PATH=\"$PATH:$HOME/node/node-v8.4.0-darwin-x64/bin:./node_modules/.bin\"" >> $BASH_ENV
      - run:
          name: "Make node dir"
          command: ls "$HOME/node/node-v8.4.0-darwin-x64" || mkdir "$HOME/node"
      - run:
          name: "Download node"
          command: ls "$HOME/node/node-v8.4.0-darwin-x64" || curl -L "https://nodejs.org/dist/v8.4.0/node-v8.4.0-darwin-x64.tar.gz" -o "$HOME/node/node-v8.4.0-darwin-x64.tar.gz"
      - run:
          name: "Extract node"
          command: ls "$HOME/node/node-v8.4.0-darwin-x64" || tar -xzf "$HOME/node/node-v8.4.0-darwin-x64.tar.gz" -C "$HOME/node/"
      - run:
          name: "Cleanup node installation"
          command: rm -f "$HOME/node/node-v8.4.0-darwin-x64.tar.gz"
      - run:
          name: "Check node installation"
          command: ls "$HOME/node/node-v8.4.0-darwin-x64"
      - run:
          name: "Checking $PATH"
          command: echo $PATH
      - run:
          name: "Check working dir"
          command: pwd
      - run:
          name: "Install npm modules"
          command: npm install
      - run:
          name: "Setup tests"
          command: bash scripts/setup_tests.sh
      - run:
          name: "Compile and run"
          command: ./node_modules/.bin/react-native run-ios

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
